config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about", to: "about#index"

  get "password",  to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"
  
  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"

  delete "logout", to: "sessions#destroy" 

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  root to: "main#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence:true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Must be ax valid email."}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to login_path, alert: "You must Login First" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end
  
    def create
      @user = User.find_by(email: params[:email])
  
      if @user.present?
        # Send email
        PasswordMailer.with(user: @user).reset.deliver_now
      end
  
      redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password."
    end
  
    def edit
      @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to login_path, alert: "Your token has expired. Please try again."
    end
  
    def update
      @user = User.find_signed!(params[:token], purpose: "password_reset")
      if @user.update(password_params)
        redirect_to login_path, notice: "Your password was reset successfully. Please sign in."
      else
        redirect_to password_reset_path, notice: "Something Went Wrong. Please Try Again."
      end
    end
  
    private
  
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password Updated!"
        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully Created Account"
        else
            render :new
        end
end
    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged In Successfuly"  
        else
            flash[:alert] = "Invalid Email or Password"
            render :new
             
    end
end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out "
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dhawan Solanki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" ></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1>Welcome to Dhawan's First Ruby on RAILS Website</h1> 
</div>

app/views/password_resets/edit.html.erb
<h1>Reset Your Password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
 <% if form.object.errors.any? %>
    <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
    <% end %>

<div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
</div>
<div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class:"form-control" %>
</div>

<div class="mb-3">
<%= form.submit "Reset Password", class: "btn btn-primary"  %>
</div>



<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Your Password?</h1>
<%= form_with url: password_reset_path do |form| %>
<div class="mb-3">
<%= form.label :email %>
<%= form.text_field :email, class: "form-control", placeholder: "Enter your Email" %>
</div>
<div class="mb-3">
<%= form.submit "Reset Password", class: "btn btn-primary"  %>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
   <div class="alert alert-warning mt-4" role="alert">
   <%= flash[:alert]  %>
</div> 
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
             <%= link_to "Dhawan Solanki", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
            <%= link_to "About", about_path, class:"nav-link" %>
        </li>
      </ul>
      
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>
      <li class="nav-item">
      <%= link_to Current.user.email , edit_password_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= button_to "logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
      <% else %>
        <%= link_to "Login", login_path, class:"nav-link" %>
        <%= link_to "Sign Up", signup_path, class:"nav-link" %>
      <% end %>
      </ul>
      
      
    </div>
  </div>
</nav>